-- Add missing fields to Mesa table
ALTER TABLE "Mesa" ADD COLUMN IF NOT EXISTS "numero" INTEGER UNIQUE;
ALTER TABLE "Mesa" ADD COLUMN IF NOT EXISTS "apodo" TEXT;
ALTER TABLE "Mesa" ADD COLUMN IF NOT EXISTS "ancho" DOUBLE PRECISION NOT NULL DEFAULT 70;
ALTER TABLE "Mesa" ADD COLUMN IF NOT EXISTS "alto" DOUBLE PRECISION NOT NULL DEFAULT 70;
