-- Add missing columns if they don't exist
ALTER TABLE "Mesa" 
ADD COLUMN IF NOT EXISTS "ancho" DOUBLE PRECISION NOT NULL DEFAULT 70,
ADD COLUMN IF NOT EXISTS "alto" DOUBLE PRECISION NOT NULL DEFAULT 70;
